<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js?v=$js_mtime"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.bundle.min.js?v=$js_mtime"></script>
<script src="js/mqtt.min.js?v=$js_mtime"></script>
<script src="js/units.js?v=$js_mtime"></script>
<script src="js/echarts.min.js?v=$js_mtime"></script>
<script src="js/luxon.min.js?v=$js_mtime"></script>
<script src="js/gauges.js?v=$js_mtime"></script>
<script src="js/site.js?v=$js_mtime"></script>
<script src="js/echarts_i18n/langEN.js?v=$js_mtime"></script>
<script src="js/echarts_i18n/langDE.js?v=$js_mtime"></script>
<script src="js/echarts_i18n/langES.js?v=$js_mtime"></script>
<script src="js/echarts_i18n/langFR.js?v=$js_mtime"></script>
<script src="js/echarts_i18n/langIT.js?v=$js_mtime"></script>
<script src="js/echarts_i18n/langNL.js?v=$js_mtime"></script>
<script src="js/echarts_i18n/langTH.js?v=$js_mtime"></script>
<script src="js/echarts_i18n/langZH.js?v=$js_mtime"></script>
