<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js?v=$js_mtime"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.bundle.min.js?v=$js_mtime"></script>
<script src="js/mqtt.min.js?v=$js_mtime"></script>
<script src="js/units.js?v=$js_mtime"></script>
<script src="js/echarts.min.js?v=$js_mtime"></script>
<script src="js/luxon.min.js?v=$js_mtime"></script>
<script src="js/gauges.js?v=$js_mtime"></script>
<script src="js/site.js?v=$js_mtime"></script>
<script src="js/lang.js?v=$js_mtime"></script>
