"stationInfo": {
    "sunrise": "$almanac.sunrise",
    "sunset": "$almanac.sunset",
    "moonPhase": "$almanac.moon_phase",
    "moonFullness": "$almanac.moon_fullness",
    "moonrise": "$almanac.moon.rise",
    "moonset": "$almanac.moon.set",
    "stationUptime": "$station.uptime.long_form",
    "stationOSUptime": "$station.os_uptime.long_form",
    "dayRain": "$day.rain.sum",
    "weekRain": "$week.rain.sum",
    "monthRain": "$month.rain.sum",
    "yearRain": "$rainyear.rain.sum",
    "24hRain": "$span(hour_delta=24).rain.sum",
    "72hRain": "$span(hour_delta=72).rain.sum",
    "30dRain": "$span(day_delta=30).rain.sum",
    "365dRain": "$span(day_delta=365).rain.sum"
}
