<div class="row d-flex align-items-center">
    <div class="col-2">
        <i class="bi-sunrise fs-3" title="$gettext('Sunrise')"></i>
    </div>
    <div class="col-4">
        <div class="text-nowrap">$almanac.sunrise</div>
    </div>
    <div class="col-2">
        <i class="bi-sunset fs-3" title="$gettext('Sunset')"></i>
    </div>
    <div class="col-4">
        <div class="text-nowrap">$almanac.sunset</div>
    </div>
</div>