<div class="row $global_station_info_classes">
    <div class="col-2">
        <i class="bi-clock-history fs-3" title="$gettext('Station Uptime')"></i>
    </div>
    <div class="col-10">
        <div class="text-nowrap">$station.uptime.long_form</div>
    </div>
</div>
<div class="row $global_station_info_classes">
    <div class="col-2">
        <i class="bi-clock-history fs-3" title="$gettext('Server Uptime')"></i>
    </div>
    <div class="col-10">
        <div class="text-nowrap">$station.os_uptime.long_form</div>
    </div>
</div>